import type { Metadata } from 'next'
import { Inter, Alumni_Sans } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })
const alumniSans = Alumni_Sans({ subsets: ['latin'], variable: '--alumni' })

export const metadata: Metadata = {
  title: 'Chickenshack',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={(inter.className, alumniSans.className)}>
        {children}
      </body>
    </html>
  )
}
